version: '2'
services:
  projects:
    image: "redmine:latest"
    expose:
      - "3000"
  files:
    image: "nuxeo:latest"
    expose:
      - "8080"
  web:
    build: ./nginx/
    links:
      - "projects"
      - "files"
    ports:
      - "80:80"
    