version: '2'
services:
  db:
    container_name: postgres
    image: "postgres:alpine"
    environment: 
      POSTGRES_PASSWORD: redmine
      POSTGRES_USER: redmine
  projects:
    container_name: redmine
    build: ./redmine/
    depends_on:
      - db
    volumes: 
      - files:/usr/src/redmine/files
    environment: 
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_USERNAME: redmine
    ports:
      - "80:3000"
  backup:
    build: ./backup/
    depends_on: 
      - db
      - projects
    volumes: 
      - ./backups:/backups
      - files:/files:ro
    environment: 
      PGHOST: db
      PGPASSWORD: redmine
      PGUSER: redmine

volumes: 
  - files:./files