#!/usr/bin/env python3
import logging
import os
import subprocess
import sys
import time

import requests

log = logging.getLogger(__name__)
stream_handler = logging.StreamHandler(sys.stderr)
log.addHandler(stream_handler)

def wait_redmine():
    while True:
        try:
            resp = requests.get('http://redmine', timeout=10)
            if resp.status_code == 200:
                return
        except Exception as e:  #pylint: disable=broad-except
            log.warning(e)

BACKUP_PATH = '/backups/dump.db'

def backup_db():
    if os.path.isfile(BACKUP_PATH):
        os.rename(BACKUP_PATH, BACKUP_PATH+'.old')
    subprocess.check_call('pg_dump > /backups/dump.db')

def main():
    wait_redmine()
    while True:
        backup_db()
        time.sleep(20)

if __name__ == '__main__':
    main()

